# Generated by Django 5.2.4 on 2025-07-13 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=2)),
                ('name', models.TextField(max_length=100)),
                ('nicename', models.TextField(max_length=100)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('numcode', models.IntegerField(null=True)),
                ('phonecode', models.IntegerField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_name', models.TextField(max_length=100)),
                ('district_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.TextField(max_length=100, null=True)),
                ('regioncode', models.IntegerField(null=True)),
                ('district', models.TextField(max_length=100, null=True)),
                ('districtcode', models.IntegerField(null=True)),
                ('ward', models.TextField(max_length=100, null=True)),
                ('wardcode', models.IntegerField(null=True)),
                ('street', models.TextField(max_length=100, null=True)),
                ('place', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.TextField(max_length=100, unique=True)),
                ('region_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_name', models.TextField(max_length=100)),
                ('ward_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.place')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.region')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupie_app.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('general_locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='tupie_app.general')),
            ],
        ),
    ]
